// ------------------------------------------------------------------------------
// <auto-generated>
// Este código fue generado por una herramienta.
// Versión de runtime: 4.0.30319.42000
// 
// Los cambios de este archivo pueden provocar un comportamiento inesperado y se perderán si
// el código se vuelve a generar.
// </auto-generated>
// ------------------------------------------------------------------------------


namespace mntDirectorio.Properties
{
	/// <summary>
    ///   Clase de recurso fuertemente tipado para buscar cadenas traducidas, etc.
    /// </summary>
	// StronglyTypedResourceBuilder generó automáticamente esta clase
	// a través de una herramienta como ResGen o Visual Studio.
	// Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
	// con la opción /str o recompile su proyecto de VS.
	[System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[System.Diagnostics.DebuggerNonUserCode()]
	[System.Runtime.CompilerServices.CompilerGenerated()]
	internal class Resources
	{

		private static System.Resources.ResourceManager resourceMan;

		private static System.Globalization.CultureInfo resourceCulture;

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources()
		{
		}

		/// <summary>
        ///   Devuelve la instancia ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (resourceMan is null)
				{
					var temp = new System.Resources.ResourceManager("mntDirectorio.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos usando esta clase de recursos fuertemente tipados.
        /// </summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}
	}
}