//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Periodos
    {
        public Nullable<int> CodEmpresa { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Periodo1 { get; set; }
        public Nullable<System.DateTime> Periodo2 { get; set; }
        public decimal Idclave { get; set; }
    }
}
