//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Suc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emp_Suc()
        {
            this.Emp_Bod = new HashSet<Emp_Bod>();
            this.Emp_PtoVta = new HashSet<Emp_PtoVta>();
        }
    
        public int Emp_Codigo { get; set; }
        public string Suc_Codigo { get; set; }
        public string Suc_Nombre { get; set; }
        public string Suc_Direccion { get; set; }
        public string Suc_RUC { get; set; }
        public string Suc_SegSocial { get; set; }
        public string Suc_IdCta { get; set; }
        public string Bod_Codigo { get; set; }
        public string Suc_IdTributario { get; set; }
        public Nullable<decimal> precioVta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Bod> Emp_Bod { get; set; }
        public virtual Emp_Datos Emp_Datos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_PtoVta> Emp_PtoVta { get; set; }
    }
}
