//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Accesos
    {
        public string IdUsuario { get; set; }
        public float IdEmpresa { get; set; }
        public string IdSistema { get; set; }
        public string IdOpcion { get; set; }
        public string IdNomOpcion { get; set; }
        public string Accesos { get; set; }
        public decimal idclavedoc { get; set; }
        public string accnvo { get; set; }
    }
}
