// ------------------------------------------------------------------------------
// <auto-generated>
// Este código fue generado por una herramienta.
// Versión de runtime:4.0.30319.42000
// 
// Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
// se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;
using Microsoft.VisualBasic;

namespace directMnt.My.Resources
{

	// StronglyTypedResourceBuilder generó automáticamente esta clase
	// a través de una herramienta como ResGen o Visual Studio.
	// Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
	// con la opción /str o recompile su proyecto de VS.
	/// <summary>
    /// Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
	[System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[DebuggerNonUserCode()]
	[System.Runtime.CompilerServices.CompilerGenerated()]
	[HideModuleName()]
	internal static class Resources
	{

		private static System.Resources.ResourceManager resourceMan;

		private static System.Globalization.CultureInfo resourceCulture;

		/// <summary>
        /// Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (ReferenceEquals(resourceMan, null))
				{
					var temp = new System.Resources.ResourceManager("directMnt.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
        /// Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        /// búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
		internal static System.Drawing.Bitmap _025
		{
			get
			{
				var obj = ResourceManager.GetObject("025", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		/// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
		internal static System.Drawing.Bitmap Buscar_16
		{
			get
			{
				var obj = ResourceManager.GetObject("Buscar_16", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		/// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
		internal static System.Drawing.Bitmap buscar_16derecha
		{
			get
			{
				var obj = ResourceManager.GetObject("buscar_16derecha", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		/// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
		internal static System.Drawing.Bitmap Delete
		{
			get
			{
				var obj = ResourceManager.GetObject("Delete", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}
	}
}