//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Par
    {
        public int Emp_Codigo { get; set; }
        public Nullable<int> DefCta_NumNiveles { get; set; }
        public Nullable<int> DefCta_NumGrupos { get; set; }
        public string DefCta_NumDigNivel { get; set; }
        public string Par_ConTipCierre { get; set; }
        public string Par_InvTipCierre { get; set; }
        public string Par_VenIVA { get; set; }
        public bool Par_VenSNEmp { get; set; }
        public bool Par_VenSNAcuDoc { get; set; }
        public string Par_ComIVA { get; set; }
        public bool Par_ComSNEmp { get; set; }
        public bool Par_ComSNAcuDoc { get; set; }
        public Nullable<int> Par_AcfNumNiv { get; set; }
        public string Par_RolCodMay { get; set; }
        public Nullable<int> Par_RolTur { get; set; }
        public string Par_SucPri { get; set; }
        public string Par_ClvDsc { get; set; }
        public string Par_ClvIVA { get; set; }
        public bool Par_AcumHis { get; set; }
        public Nullable<int> Par_FecDes { get; set; }
        public Nullable<int> Par_Numerodigitos { get; set; }
        public Nullable<int> Par_LimAtrasoEntrada { get; set; }
        public Nullable<int> Par_LimExtraSalida { get; set; }
        public Nullable<int> Par_LimExtraEntrada { get; set; }
        public string Par_DocPrincipalVta { get; set; }
        public Nullable<byte> Par_Cheques { get; set; }
        public string Par_PagoCompras { get; set; }
        public Nullable<int> DefCta_NumNiveles1 { get; set; }
        public Nullable<int> DefCta_NumGrupos1 { get; set; }
        public string DefCta_NumDigNivel1 { get; set; }
        public Nullable<decimal> DefCtaV { get; set; }
        public Nullable<int> Par_DigitosCostos { get; set; }
        public Nullable<int> Par_DigitosPrecios { get; set; }
        public Nullable<byte> Par_CruceDocSucursal { get; set; }
        public string par_PathImagenes { get; set; }
        public Nullable<int> par_DiasMensualesAcf { get; set; }
        public string Emp_PathImagenes { get; set; }
        public Nullable<int> Emp_DiasMensualesAcf { get; set; }
        public Nullable<int> Prspto_NumNiveles { get; set; }
        public Nullable<int> Prspto_NumGrupos { get; set; }
        public string Prspto_NumDigNivel { get; set; }
        public string path_tmpServer { get; set; }
        public string CtaLocalEmail { get; set; }
    
        public virtual Emp_Datos Emp_Datos { get; set; }
    }
}
