//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Arch
    {
        public int Emp_Codigo { get; set; }
        public string Arch_Tipo { get; set; }
        public string Arch_Nom { get; set; }
    
        public virtual Emp_Datos Emp_Datos { get; set; }
    }
}
