//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Datos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emp_Datos()
        {
            this.Emp_Arch = new HashSet<Emp_Arch>();
            this.Emp_Suc = new HashSet<Emp_Suc>();
        }
    
        public int Emp_codigo { get; set; }
        public string Emp_Nombre { get; set; }
        public string Emp_Pais { get; set; }
        public string Emp_Provincia { get; set; }
        public string Emp_Ciudad { get; set; }
        public string Emp_Cantón { get; set; }
        public string Emp_Dirección { get; set; }
        public string Emp_Telefono_1 { get; set; }
        public string Emp_Telefono_2 { get; set; }
        public string Emp_Fax { get; set; }
        public string Emp_Casilla { get; set; }
        public string Emp_Email { get; set; }
        public string Emp_RUC { get; set; }
        public string Emp_SegSocial { get; set; }
        public string Emp_Presidente { get; set; }
        public string Emp_Gerente { get; set; }
        public string Emp_RepLegal { get; set; }
        public string Emp_Contador { get; set; }
        public string Emp_Logotipo { get; set; }
        public bool Emp_Defecto { get; set; }
        public string Emp_Lic1 { get; set; }
        public string Emp_Lic2 { get; set; }
        public string Emp_Lic3 { get; set; }
        public string Emp_TipoBase { get; set; }
        public string Emp_Lic4 { get; set; }
        public string Emp_Lic5 { get; set; }
        public string Emp_Lic6 { get; set; }
        public string Emp_PathImagenes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Arch> Emp_Arch { get; set; }
        public virtual Emp_Par Emp_Par { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Suc> Emp_Suc { get; set; }
    }
}
