//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DaxsysEntities : DbContext
    {
        public DaxsysEntities()
            : base("name=DaxsysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emp_Arch> Emp_Arch { get; set; }
        public virtual DbSet<Emp_Bod> Emp_Bod { get; set; }
        public virtual DbSet<Emp_Datos> Emp_Datos { get; set; }
        public virtual DbSet<Emp_Par> Emp_Par { get; set; }
        public virtual DbSet<Emp_PtoVta> Emp_PtoVta { get; set; }
        public virtual DbSet<Emp_Suc> Emp_Suc { get; set; }
        public virtual DbSet<sys_Accesos> sys_Accesos { get; set; }
        public virtual DbSet<sys_Bodegas> sys_Bodegas { get; set; }
        public virtual DbSet<sys_Sucursales> sys_Sucursales { get; set; }
        public virtual DbSet<Emp_Periodos> Emp_Periodos { get; set; }
        public virtual DbSet<sys_ptoVta> sys_ptoVta { get; set; }
    }
}
