//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Sucursales
    {
        public string IdUsuario { get; set; }
        public byte IdEmpresa { get; set; }
        public string CodSucursal { get; set; }
        public string AutorizaSuc { get; set; }
    }
}
