Imports System.Data.SqlClient

Public Class ActivosFijos

    Public CODIGO As String = ""
    Public NOMBRE As String = ""
    Public TIPOACTIVO As String = ""
    Public CATEGORIA As String = ""
    Public CLASE As String = ""
    Public GRUPO As String = ""
    Public SUBGRUPO As String = ""
    Public MARCA As String = ""
    Public SERIE As String = ""
    Public NROLOTE As String = ""
    Public CENTROCOSTO As String = ""
    Public CODACTIVOPRINCIPAL As String = ""
    Public ESACTIVOCOMPUESTO As Integer
    Public DESCRIPCION As String = ""
    Public UBICASUCURSAL As String = ""
    Public UBICADEPARTAMENTO As String = ""
    Public UBICASECCION As String = ""
    Public RESPONSABLE As String = ""
    Public ESTADO As String = ""
    Public TASADEPRESIACION As Double = 0.0
    Public FECINGRESO As Date = "0:0"
    Public COSTOINGRESO As Double = 0.0
    Public DOCTIPINGRESO As String = ""
    Public DOCNUMINGRESO As Double = 0.0
    Public FECSALIDA As Date = "0:0"
    Public DOCTIPSALIDA As String = ""
    Public DOCNUMSALIDA As Double = 0.0
    Public CTACONTABLE1 As String = ""
    Public CTACONTABLE2 As String = ""
    Public CTACONTABLE3 As String = ""
    Public CTACONTABLE4 As String = ""
    Public VALORRESIDUAL As Double = 0.0
    Public TIPODEPRECIACIONCONT As Integer = 0
    Public TIPODEPRECIACIONTRIBUTA As Integer = 0
    Public VIDAUTILCONT As Double = 0.0
    Public VIDAUTILTRIBUTA As Double = 0.0
    Public UNIDADESPRODUCCIONCONT As Double = 0.0
    Public UNIDADESPRODUCCIONTRIB As Double = 0.0
    Public TASADEPCONT As Double = 0.0
    Public TASADEPTRIBUT As Double = 0.0
    Public VALORACTUALCONT As Double = 0.0
    Public VALORACTUALTRIBUT As Double = 0.0
    Public ULTIMOAÑOCALC As Double = 0.0
    Public ULTIMOMESCALC As Double = 0.0
    Public USUARIOCREA As String = ""
    Public FECHACREA As Date = "0:0"
    Public USUARIOMODIFICA As String = ""
    Public FECHAMODIFICA As Date = "0:0"
    Public TEXTO1 As String = ""
    Public TEXTO2 As String = ""
    Public TEXTO3 As String = ""
    Public TEXTO4 As String = ""
    Public TEXTO5 As String = ""
    Public TEXTO6 As String = ""
    Public TEXTO7 As String = ""
    Public TEXTO8 As String = ""
    Public TEXTO9 As String = ""
    Public TEXTO10 As String = ""
    Public DET1 As String = ""
    Public DET2 As String = ""
    Public DET3 As String = ""
    Public DET4 As String = ""
    Public DET5 As String = ""
    Public VALOR1 As Double = 0.0
    Public VALOR2 As Double = 0.0
    Public VALOR3 As Double = 0.0
    Public VALOR4 As Double = 0.0
    Public VALOR5 As Double = 0.0
    Public FECHA1 As Date = "0:0"
    Public FECHA2 As Date = "0:0"
    Public FECHA3 As Date = "0:0"
    Public LOGICO1 As Integer = 0
    Public LOGICO2 As Integer = 0
    Public LOGICO3 As Integer = 0
    Public IMAGEN As String = ""
    Public CANTIDAD As Double = 0.0
    Public ASEGURADORA As String = ""
    Public NCONTRATO As Double = 0.0
    Public FECHAINGSEGURO As Date = "0:0"
    Public FECHASALSEGURO As Date = "0:0"
    Public MONTOASEGURADO As Double = 0.0
    Public DEDUCIBLE As Double = 0.0
    Public PAGOMENSUAL As Double = 0.0
    Public MONEDA As String = ""
    Public PARIDAD As Double = 0.0
    Public ESCOMPONENTE As Integer = 0

    '************************************
    Dim ssql As String = ""
    Public conectar As SqlConnection
    Dim cmd As New SqlCommand(ssql, conectar)
    Dim dat As SqlDataReader

    Public Sub Guardar()
        ssql = "INSERT INTO AdcAcf ("
        ssql += "Codigo,"
        ssql += "Nombre,"
        ssql += "TipoActivo,"
        ssql += "Categoria,"
        ssql += "Clase,"
        ssql += "Grupo,"
        ssql += "Subgrupo,"
        ssql += "Marca,"
        ssql += "Serie,"
        ssql += "NroLote,"
        ssql += "CentroCosto,"
        ssql += "CodActivoPrincipal,"
        ssql += "EsActivoCompuesto,"
        ssql += "Descripcion,"
        ssql += "UbicaSucursal,"
        ssql += "UbicaDepartamento,"
        ssql += "UbicaSeccion,"
        ssql += "Responsable,"
        ssql += "Estado,"
        ssql += "TasaDepreciacion,"
        ssql += "FecIngreso,"
        ssql += "CostoIngreso,"
        ssql += "DocTipIngreso,"
        ssql += "DocNumIngreso,"
        ssql += "FecSalida,"
        ssql += "DocTipSalida,"
        ssql += "DocNumSalida,"
        ssql += "CtaContable1,"
        ssql += "CtaContable2,"
        ssql += "CtaContable3,"
        ssql += "CtaContable4,"
        ssql += "ValorResidual,"
        ssql += "TipoDepreciacionCont,"
        ssql += "TipoDepreciacionTributa,"
        ssql += "VidaUtilCont,"
        ssql += "VidaUtilTributa,"
        ssql += "UnidacesProduccionCont,"
        ssql += "UnidadesProduccionTribut,"
        ssql += "TasaDepCont,"
        ssql += "TasaDepTribut,"
        ssql += "ValorActualCont,"
        ssql += "ValorActualTribut,"
        ssql += "UltimoAñoCalc,"
        ssql += "UltimoMesCalc,"
        ssql += "UsuarioCrea,"
        ssql += "FechaCrea,"
        ssql += "UsuarioModifica,"
        ssql += "FechaModifica,"
        ssql += "Texto1,"
        ssql += "Texto2,"
        ssql += "Texto3,"
        ssql += "Texto4,"
        ssql += "Texto5,"
        ssql += "Texto6,"
        ssql += "Texto7,"
        ssql += "Texto8,"
        ssql += "Texto9,"
        ssql += "Texto10,"
        ssql += "Det1,"
        ssql += "Det2,"
        ssql += "Det3,"
        ssql += "Det4,"
        ssql += "Det5,"
        ssql += "Valor1,"
        ssql += "Valor2,"
        ssql += "Valor3,"
        ssql += "Valor4,"
        ssql += "Valor5,"
        ssql += "Fecha1,"
        ssql += "Fecha2,"
        ssql += "Fecha3,"
        ssql += "Logico1,"
        ssql += "Logico2,"
        ssql += "Logico3,"
        ssql += "Imagen,"
        ssql += "Cantidad,"
        ssql += "Aseguradora,"
        ssql += "NContrato,"
        ssql += "FechaIngSeguro,"
        ssql += "FechaSalSeguro,"
        ssql += "MontoAsegurado,"
        ssql += "Deducible,"
        ssql += "PagoMensual,"
        ssql += "Moneda,"
        ssql += "Paridad, "
        ssql += "EsComponente "
        ssql += ")"
        ssql += "VALUES("
        ssql += "'" & CODIGO & "',"
        ssql += "'" & NOMBRE & "',"
        ssql += "'" & TIPOACTIVO & "',"
        ssql += "'" & CATEGORIA & "',"
        ssql += "'" & CLASE & "',"
        ssql += "'" & GRUPO & "',"
        ssql += "'" & SUBGRUPO & "',"
        ssql += "'" & MARCA & "',"
        ssql += "'" & SERIE & "',"
        ssql += "'" & NROLOTE & "',"
        ssql += "'" & CENTROCOSTO & "',"
        ssql += "'" & CODACTIVOPRINCIPAL & "',"
        ssql += "" & ESACTIVOCOMPUESTO & ","
        ssql += "'" & DESCRIPCION & "',"
        ssql += "'" & UBICASUCURSAL & "',"
        ssql += "'" & UBICADEPARTAMENTO & "',"
        ssql += "'" & UBICASECCION & "',"
        ssql += "'" & RESPONSABLE & "',"
        ssql += "'" & ESTADO & "',"
        ssql += "" & TASADEPRESIACION & ","
        ssql += "'" & FECINGRESO & "',"
        ssql += "" & COSTOINGRESO & ","
        ssql += "'" & DOCTIPINGRESO & "',"
        ssql += "" & DOCNUMINGRESO & ","
        ssql += "'" & FECSALIDA & "',"
        ssql += "'" & DOCTIPSALIDA & "',"
        ssql += "" & DOCNUMSALIDA & ","
        ssql += "'" & CTACONTABLE1 & "',"
        ssql += "'" & CTACONTABLE2 & "',"
        ssql += "'" & CTACONTABLE3 & "',"
        ssql += "'" & CTACONTABLE4 & "',"
        ssql += "" & VALORRESIDUAL & ","
        ssql += "'" & TIPODEPRECIACIONCONT & "',"
        ssql += "'" & TIPODEPRECIACIONTRIBUTA & "',"
        ssql += "" & VIDAUTILCONT & ","
        ssql += "" & VIDAUTILTRIBUTA & ","
        ssql += "" & UNIDADESPRODUCCIONCONT & ","
        ssql += "" & UNIDADESPRODUCCIONTRIB & ","
        ssql += "" & TASADEPCONT & ","
        ssql += "" & TASADEPTRIBUT & ","
        ssql += "" & VALORACTUALCONT & ","
        ssql += "" & VALORACTUALTRIBUT & ","
        ssql += "" & ULTIMOAÑOCALC & ","
        ssql += "" & ULTIMOMESCALC & ","
        ssql += "'" & USUARIOCREA & "',"
        ssql += "'" & FECHACREA & "',"
        ssql += "'" & USUARIOMODIFICA & "',"
        ssql += "'" & FECHAMODIFICA & "',"
        ssql += "'" & TEXTO1 & "',"
        ssql += "'" & TEXTO2 & "',"
        ssql += "'" & TEXTO3 & "',"
        ssql += "'" & TEXTO4 & "',"
        ssql += "'" & TEXTO5 & "',"
        ssql += "'" & TEXTO6 & "',"
        ssql += "'" & TEXTO7 & "',"
        ssql += "'" & TEXTO8 & "',"
        ssql += "'" & TEXTO9 & "',"
        ssql += "'" & TEXTO10 & "',"
        ssql += "'" & DET1 & "',"
        ssql += "'" & DET2 & "',"
        ssql += "'" & DET3 & "',"
        ssql += "'" & DET4 & "',"
        ssql += "'" & DET5 & "',"
        ssql += "" & VALOR1 & ","
        ssql += "" & VALOR2 & ","
        ssql += "" & VALOR3 & ","
        ssql += "" & VALOR4 & ","
        ssql += "" & VALOR5 & ","
        ssql += "'" & FECHA1 & "',"
        ssql += "'" & FECHA2 & "',"
        ssql += "'" & FECHA3 & "',"
        ssql += "'" & LOGICO1 & "',"
        ssql += "" & LOGICO2 & ","
        ssql += "" & LOGICO3 & ","
        ssql += "'" & IMAGEN & "',"
        ssql += "" & CANTIDAD & ","
        ssql += "'" & ASEGURADORA & "',"
        ssql += "" & NCONTRATO & ","
        ssql += "'" & FECHAINGSEGURO & "',"
        ssql += "'" & FECHASALSEGURO & "',"
        ssql += "" & MONTOASEGURADO & ","
        ssql += "" & DEDUCIBLE & ","
        ssql += "" & PAGOMENSUAL & ","
        ssql += "'" & MONEDA & "',"
        ssql += "" & PARIDAD & ","
        ssql += "" & ESCOMPONENTE & ")"
        EjecutarComandos(ssql)
    End Sub
    Public Sub Actualizar(ByVal cod As String)
        ssql = "UPDATE AdcAcf set "
        ssql += "Nombre  ='" & NOMBRE & "',"
        ssql += "TipoActivo  ='" & TIPOACTIVO & "',"
        ssql += "Categoria  ='" & CATEGORIA & "',"
        ssql += "Clase  ='" & CLASE & "',"
        ssql += "Grupo  ='" & GRUPO & "',"
        ssql += "Subgrupo  ='" & SUBGRUPO & "',"
        ssql += "Marca  ='" & MARCA & "',"
        ssql += "Serie  ='" & SERIE & "',"
        ssql += "NroLote  ='" & NROLOTE & "',"
        ssql += "CentroCosto  ='" & CENTROCOSTO & "',"
        ssql += "CodActivoPrincipal  ='" & CODACTIVOPRINCIPAL & "',"
        ssql += "EsActivoCompuesto  =" & ESACTIVOCOMPUESTO & ","
        ssql += "Descripcion  ='" & DESCRIPCION & "',"
        ssql += "UbicaSucursal  ='" & UBICASUCURSAL & "',"
        ssql += "UbicaDepartamento  ='" & UBICADEPARTAMENTO & "',"
        ssql += "UbicaSeccion  ='" & UBICASECCION & "',"
        ssql += "Responsable  ='" & RESPONSABLE & "',"
        ssql += "Estado  ='" & ESTADO & "',"
        ssql += "TasaDepreciacion  =" & TASADEPRESIACION & ","
        ssql += "FecIngreso  ='" & FECINGRESO & "',"
        ssql += "CostoIngreso  =" & COSTOINGRESO & ","
        ssql += "DocTipIngreso  ='" & DOCTIPINGRESO & "',"
        ssql += "DocNumIngreso  =" & DOCNUMINGRESO & ","
        ssql += "FecSalida  ='" & FECSALIDA & "',"
        ssql += "DocTipSalida  ='" & DOCTIPSALIDA & "',"
        ssql += "DocNumSalida  =" & DOCNUMSALIDA & ","
        ssql += "CtaContable1  ='" & CTACONTABLE1 & "',"
        ssql += "CtaContable2  ='" & CTACONTABLE2 & "',"
        ssql += "CtaContable3  ='" & CTACONTABLE3 & "',"
        ssql += "CtaContable4  ='" & CTACONTABLE4 & "',"
        ssql += "ValorResidual  =" & VALORRESIDUAL & ","
        ssql += "TipoDepreciacionCont  ='" & TIPODEPRECIACIONCONT & "',"
        ssql += "TipoDepreciacionTributa  ='" & TIPODEPRECIACIONTRIBUTA & "',"
        ssql += "VidaUtilCont  =" & VIDAUTILCONT & ","
        ssql += "VidaUtilTributa  =" & VIDAUTILTRIBUTA & ","
        ssql += "UnidacesProduccionCont  =" & UNIDADESPRODUCCIONCONT & ","
        ssql += "UnidadesProduccionTribut  =" & UNIDADESPRODUCCIONTRIB & ","
        ssql += "TasaDepCont  =" & TASADEPCONT & ","
        ssql += "TasaDepTribut  =" & TASADEPTRIBUT & ","
        ssql += "ValorActualCont  =" & VALORACTUALCONT & ","
        ssql += "ValorActualTribut  =" & VALORACTUALTRIBUT & ","
        ssql += "UltimoAñoCalc  =" & ULTIMOAÑOCALC & ","
        ssql += "UltimoMesCalc  =" & ULTIMOMESCALC & ","
        ssql += "UsuarioCrea  ='" & USUARIOCREA & "',"
        ssql += "FechaCrea  ='" & FECHACREA & "',"
        ssql += "UsuarioModifica  ='" & USUARIOMODIFICA & "',"
        ssql += "FechaModifica  ='" & FECHAMODIFICA & "',"
        ssql += "Texto1  ='" & TEXTO1 & "',"
        ssql += "Texto2  ='" & TEXTO2 & "',"
        ssql += "Texto3  ='" & TEXTO3 & "',"
        ssql += "Texto4  ='" & TEXTO4 & "',"
        ssql += "Texto5  ='" & TEXTO5 & "',"
        ssql += "Texto6  ='" & TEXTO6 & "',"
        ssql += "Texto7  ='" & TEXTO7 & "',"
        ssql += "Texto8  ='" & TEXTO8 & "',"
        ssql += "Texto9  ='" & TEXTO9 & "',"
        ssql += "Texto10  ='" & TEXTO10 & "',"
        ssql += "Det1  ='" & DET1 & "',"
        ssql += "Det2  ='" & DET2 & "',"
        ssql += "Det3  ='" & DET3 & "',"
        ssql += "Det4  ='" & DET4 & "',"
        ssql += "Det5  ='" & DET5 & "',"
        ssql += "Valor1  =" & VALOR1 & ","
        ssql += "Valor2  =" & VALOR2 & ","
        ssql += "Valor3  =" & VALOR3 & ","
        ssql += "Valor4  =" & VALOR4 & ","
        ssql += "Valor5  =" & VALOR5 & ","
        ssql += "Fecha1  ='" & FECHA1 & "',"
        ssql += "Fecha2  ='" & FECHA2 & "',"
        ssql += "Fecha3  ='" & FECHA3 & "',"
        ssql += "Logico1  ='" & LOGICO1 & "',"
        ssql += "Logico2  =" & LOGICO2 & ","
        ssql += "Logico3  =" & LOGICO3 & ","
        ssql += "Imagen  ='" & IMAGEN & "',"
        ssql += "Cantidad  =" & CANTIDAD & ","
        ssql += "Aseguradora  ='" & ASEGURADORA & "',"
        ssql += "NContrato  =" & NCONTRATO & ","
        ssql += "FechaIngSeguro  ='" & FECHAINGSEGURO & "',"
        ssql += "FechaSalSeguro  ='" & FECHASALSEGURO & "',"
        ssql += "MontoAsegurado  =" & MONTOASEGURADO & ","
        ssql += "Deducible  =" & DEDUCIBLE & ","
        ssql += "PagoMensual  =" & PAGOMENSUAL & ","
        ssql += "Moneda  ='" & MONEDA & "',"
        ssql += "Paridad =" & PARIDAD & ","
        ssql += "EsComponente  =" & ESCOMPONENTE
        If cod <> "" Then ssql += " where Codigo ='" & cod & "'"
        EjecutarComandos(ssql)
    End Sub
    Public Sub Eliminar(ByVal cod As String)
        ssql = "delete from AdcAcf "
        If cod <> "" Then ssql += " where Codigo='" & cod & "'"
        EjecutarComandos(ssql)
    End Sub
    Private Sub EjecutarComandos(ByVal comando As String)
        cmd.Connection = conectar
        cmd.CommandText = comando
        If conectar.State = ConnectionState.Open Then conectar.Close()
        conectar.Open()
        cmd.ExecuteNonQuery()
        conectar.Close()
    End Sub
End Class
