if exists(select * from sys.objects where name ='ADCDOC_GENERAR_INV')
begin
DROP PROCEDURE [dbo].[ADCDOC_GENERAR_INV]
end
GO

 CREATE PROCEDURE [dbo].[ADCDOC_GENERAR_INV]
(@Doc_sucursal char(3)='',
@Doc_Bodega varchar(3)='',
@Opc_documento char(3)='',
@Doc_numero numeric(18,0)=0,
@Doc_docnombre varchar(40)='',
@Doc_TipoDoc varchar(3)='',
@Doc_DocSop varchar(3)='',
@Doc_NumSop numeric(18,0)='',
@Doc_fecha datetime=null,
@Doc_Hora datetime=null,
@Doc_extension varchar(15)='',
@Doc_codper varchar(15)='',
@Doc_codusu varchar(15)='',
@Doc_venabre varchar(15)='',
@Doc_porceniva numeric(19,4)=0,
@Doc_valoriva numeric(19,4)=0,
@Doc_totciva numeric(19,4)=0,
@Doc_totsiva numeric(19,4)=0,
@Doc_nombredes1 varchar(40)='',
@Doc_nombredes2 varchar(40)='',
@Doc_nombredes3 varchar(40)='',
@Doc_nombredes4 varchar(40)='',
@Doc_porcendes1 numeric(19,4)=0,
@Doc_porcendes2 numeric(19,4)=0,
@Doc_porcendes3 numeric(19,4)=0,
@Doc_porcendes4 numeric(19,4)=0,
@Doc_valordes1 numeric(19,4)=0,
@Doc_valordes2 numeric(19,4)=0,
@Doc_valordes3 numeric(19,4)=0,
@Doc_valordes4 numeric(19,4)=0,
@Doc_valor numeric(19,4)=0,
@Doc_valorabon numeric(19,4)=0,
@Doc_detalle varchar(512)='',
@Doc_NombreImp varchar(80)='',
@Doc_CiRuc varchar(20)='',
@Doc_Direccion varchar(80)='',
@Doc_Telefono1 varchar(15)='',
@Doc_Telefono2 varchar(15)='',
@Doc_DepDes varchar(50)='',
@Doc_TotDesArt numeric(19,4)=0,
@Doc_TotDesSer numeric(19,4)=0,
@Doc_TotArtCIva numeric(19,4)=0,
@Doc_TotArtSIva numeric(19,4)=0,
@Doc_TotSerCIva numeric(19,4)=0,
@Doc_TotSerSIva numeric(19,4)=0,
@Doc_TotAcf numeric(19,4)=0,
@Doc_Contado numeric(19,4)=0,
@Doc_FechaEfe datetime=null,
@Doc_Estado int=0,
@Doc_Oculto int=0,
@Doc_Contabilidad money=null,
@Doc_Banco money=null,
@Doc_Inventario smallint=0,
@Doc_Ventas smallint=0,
@Doc_Compras smallint=0,
@Doc_Activo smallint=0,
@Doc_Adicional1 numeric(19,4)=0,
@Doc_Adicional2 numeric(19,4)=0,
@Doc_NumeroExterno numeric(18,0)=0,
@Doc_NroIdDoc varchar(50)='',
@Doc_SaldoActualCli numeric(19,4)=0,
@Doc_SaldoFinalCli numeric(19,4)=0,
@Doc_FechaModifica datetime=null,
@Doc_CentroCosto varchar(20)='',
@IdClaveDoc numeric(18,0)=0,
@IdClaveDocSop numeric(18,0)=0,
@doc_SucursalDestino varchar(20)='',
@doc_SucDestino varchar(20)='',
@doc_BodDestino varchar(20)='',
@Doc_NroLoteDoc varchar(20)='',
@doc_BancoOrigen varchar(20)='',
@doc_BancoDestino varchar(20)='',
@doc_NumeroCheque varchar(20)='',
@doc_Aceptado bit=0,
@Doc_Liquidado bit=0,
@Doc_CobraCheque varchar(10)='',
@doc_TotDesCIva numeric(18,2)=0,
@doc_TotDesSiva numeric(18,2)=0,
@Periodo1 datetime=null,
@Periodo2 datetime=null,
@FacDesde datetime=null,
@FacHasta datetime=null,
@Habitacion varchar(15)='',
@Mesa varchar(15)='',
@TipoPeriodo varchar(20)='',
@Adi_NroAutSri varchar(20)='',
@Adi_SustTrib varchar(20)='',
@Adi_TipoDocSri varchar(20)='',
@Adi_SNDevIva char(1)='',
@Adi_FechContab datetime =null,
@Adi_CodigoNSR varchar(20)='',
@Dia_Status char(1)='',
@Moneda varchar(20)='',
@Paridad numeric(22,8)=0,
@ParidadBiMoneda numeric(22,8)=0,
@PaisDestino varchar(80)='',
@ProvinciaDestino varchar(80)='',
@CiudadDestino varchar(80)='',
@DireccionDestino varchar(80)='',
@Destinatario varchar(80)='',
@RucDestinatario varchar(80)='',
@ContactoDestino varchar(80)='',
@FecIniTransporte datetime =null,
@FecFinTransporte datetime = null,
@Transportista varchar(80)='',
@RucTransportista varchar(15)='',
@TipoTransporte varchar(20)='',
@EsContable varchar(1)='',
@AuxVar1 varchar(128)='',
@AuxVar2 varchar(128)='',
@AuxVar3 varchar(128)='',
@AuxVar4 varchar(128)='',
@AuxVar5 varchar(128)='',
@AuxVar6 varchar(128)='',
@AuxVar7 varchar(128)='',
@AuxVar8 varchar(128)='',
@AuxVar9 varchar(128)='',
@AuxVar10 varchar(128)='',
@AuxVar11 varchar(128)='',
@AuxVar12 varchar(128)='',
@AuxFec1 datetime= null,
@AuxFec2 datetime= null,
@AuxFec3 datetime= null,
@AuxLog1 varchar(1)='',
@AuxLog2 varchar(1)='',
@AuxLog3 varchar(1)='',
@AuxNum1 numeric(22,8)=0,
@AuxNum2 numeric(22,8)=0,
@AuxNum3 numeric(22,8)=0,
@AuxNum4 numeric(22,8)=0,
@AuxNum5 numeric(22,8)=0,
@AuxNum6 numeric(22,8)=0,
@AuxNum7 numeric(22,8)=0,
@AuxNum8 numeric(22,8)=0,
@AuxNum9 numeric(22,8)=0,
@AuxNum10 numeric(22,8)=0,
@AuxNum11 numeric(22,8)=0,
@AuxNum12 numeric(22,8)=0,
@doc_Anticipo bit=0,
@Consolidar bit=0,
@TipDocConsolida varchar(10)='',
@NroDocConsolida numeric(18,0)=0,
@Contabilizar bit=0,
@ProductoProduccion varchar(50)='',
@Mesero varchar(125)='',
@BaseImp1 numeric(22,4)=0,
@BaseImp2 numeric(22,4)=0,
@BaseImp3 numeric(22,4)=0,
@PorcImp1 numeric(22,4)=0,
@PorcImp2 numeric(22,4)=0,
@PorcImp3 numeric(22,4)=0,
@ValorImp1 numeric(22,4)=0,
@ValorImp2 numeric(22,4)=0,
@ValorImp3 numeric(22,4)=0,
@Ocupantes numeric(5,0)=0)
AS
BEGIN 
insert into AdcDoc 
		(Doc_sucursal,
		Doc_Bodega,
		Opc_documento,
		Doc_numero,
		Doc_docnombre,
		Doc_TipoDoc,
		Doc_DocSop,
		Doc_NumSop,
		Doc_fecha,
		Doc_Hora,
		Doc_extension,
		Doc_codper,
		Doc_codusu,
		Doc_venabre,
		Doc_porceniva,
		Doc_valoriva,
		Doc_totciva,
		Doc_totsiva,
		Doc_nombredes1,
		Doc_nombredes2,
		Doc_nombredes3,
		Doc_nombredes4,
		Doc_porcendes1,
		Doc_porcendes2,
		Doc_porcendes3,
		Doc_porcendes4,
		Doc_valordes1,
		Doc_valordes2,
		Doc_valordes3,
		Doc_valordes4,
		Doc_valor,
		Doc_valorabon,
		Doc_detalle,
		Doc_NombreImp,
		Doc_CiRuc,
		Doc_Direccion,
		Doc_Telefono1,
		Doc_Telefono2,
		Doc_DepDes,
		Doc_TotDesArt,
		Doc_TotDesSer,
		Doc_TotArtCIva,
		Doc_TotArtSIva,
		Doc_TotSerCIva,
		Doc_TotSerSIva,
		Doc_TotAcf,
		Doc_Contado,
		Doc_FechaEfe,
		Doc_Estado,
		Doc_Oculto,
		Doc_Contabilidad,
		Doc_Banco,
		Doc_Inventario,
		Doc_Ventas,
		Doc_Compras,
		Doc_Activo,
		Doc_Adicional1,
		Doc_Adicional2,
		Doc_NumeroExterno,
		Doc_NroIdDoc,
		Doc_SaldoActualCli,
		Doc_SaldoFinalCli,
		Doc_FechaModifica,
		Doc_CentroCosto,
		IdClaveDoc,
		IdClaveDocSop,
		doc_SucursalDestino,
		doc_SucDestino,
		doc_BodDestino,
		Doc_NroLoteDoc,
		doc_BancoOrigen,
		doc_BancoDestino,
		doc_NumeroCheque,
		doc_Aceptado,
		Doc_Liquidado,
		Doc_CobraCheque,
		doc_TotDesCIva,
		doc_TotDesSiva,
		Periodo1,
		Periodo2,
		FacDesde,
		FacHasta,
		Habitacion,
		Mesa,
		TipoPeriodo,
		Adi_NroAutSri,
		Adi_SustTrib,
		Adi_TipoDocSri,
		Adi_SNDevIva,
		Adi_FechContab,
		Adi_CodigoNSR,
		Dia_Status,
		Moneda,
		Paridad,
		ParidadBiMoneda,
		PaisDestino,
		ProvinciaDestino,
		CiudadDestino,
		DireccionDestino,
		Destinatario,
		RucDestinatario,
		ContactoDestino,
		FecIniTransporte,
		FecFinTransporte,
		Transportista,
		RucTransportista,
		TipoTransporte,
		EsContable,
		AuxVar1,
		AuxVar2,
		AuxVar3,
		AuxVar4,
		AuxVar5,
		AuxVar6,
		AuxVar7,
		AuxVar8,
		AuxVar9,
		AuxVar10,
		AuxVar11,
		AuxVar12,
		AuxFec1,
		AuxFec2,
		AuxFec3,
		AuxLog1,
		AuxLog2,
		AuxLog3,
		AuxNum1,
		AuxNum2,
		AuxNum3,
		AuxNum4,
		AuxNum5,
		AuxNum6,
		AuxNum7,
		AuxNum8,
		AuxNum9,
		AuxNum10,
		AuxNum11,
		AuxNum12,
		doc_Anticipo,
		Consolidar,
		TipDocConsolida,
		NroDocConsolida,
		Contabilizar,
		ProductoProduccion,
		Mesero,
		BaseImp1,
		BaseImp2,
		BaseImp3,
		PorcImp1,
		PorcImp2,
		PorcImp3,
		ValorImp1,
		ValorImp2,
		ValorImp3,
		Ocupantes)
		values
		(@Doc_sucursal,
		@Doc_Bodega,
		@Opc_documento,
		@Doc_numero,
		@Doc_docnombre,
		@Doc_TipoDoc,
		@Doc_DocSop,
		@Doc_NumSop,
		@Doc_fecha,
		@Doc_Hora,
		@Doc_extension,
		@Doc_codper,
		@Doc_codusu,
		@Doc_venabre,
		@Doc_porceniva,
		@Doc_valoriva,
		@Doc_totciva,
		@Doc_totsiva,
		@Doc_nombredes1,
		@Doc_nombredes2,
		@Doc_nombredes3,
		@Doc_nombredes4,
		@Doc_porcendes1,
		@Doc_porcendes2,
		@Doc_porcendes3,
		@Doc_porcendes4,
		@Doc_valordes1,
		@Doc_valordes2,
		@Doc_valordes3,
		@Doc_valordes4,
		@Doc_valor,
		@Doc_valorabon,
		@Doc_detalle,
		@Doc_NombreImp,
		@Doc_CiRuc,
		@Doc_Direccion,
		@Doc_Telefono1,
		@Doc_Telefono2,
		@Doc_DepDes,
		@Doc_TotDesArt,
		@Doc_TotDesSer,
		@Doc_TotArtCIva,
		@Doc_TotArtSIva,
		@Doc_TotSerCIva,
		@Doc_TotSerSIva,
		@Doc_TotAcf,
		@Doc_Contado,
		@Doc_FechaEfe,
		@Doc_Estado,
		@Doc_Oculto,
		@Doc_Contabilidad,
		@Doc_Banco,
		@Doc_Inventario,
		@Doc_Ventas,
		@Doc_Compras,
		@Doc_Activo,
		@Doc_Adicional1,
		@Doc_Adicional2,
		@Doc_NumeroExterno,
		@Doc_NroIdDoc,
		@Doc_SaldoActualCli,
		@Doc_SaldoFinalCli,
		@Doc_FechaModifica,
		@Doc_CentroCosto,
		@IdClaveDoc,
		@IdClaveDocSop,
		@doc_SucursalDestino,
		@doc_SucDestino,
		@doc_BodDestino,
		@Doc_NroLoteDoc,
		@doc_BancoOrigen,
		@doc_BancoDestino,
		@doc_NumeroCheque,
		@doc_Aceptado,
		@Doc_Liquidado,
		@Doc_CobraCheque,
		@doc_TotDesCIva,
		@doc_TotDesSiva,
		@Periodo1,
		@Periodo2,
		@FacDesde,
		@FacHasta,
		@Habitacion,
		@Mesa,
		@TipoPeriodo,
		@Adi_NroAutSri,
		@Adi_SustTrib,
		@Adi_TipoDocSri,
		@Adi_SNDevIva,
		@Adi_FechContab,
		@Adi_CodigoNSR,
		@Dia_Status,
		@Moneda,
		@Paridad,
		@ParidadBiMoneda,
		@PaisDestino,
		@ProvinciaDestino,
		@CiudadDestino,
		@DireccionDestino,
		@Destinatario,
		@RucDestinatario,
		@ContactoDestino,
		@FecIniTransporte,
		@FecFinTransporte,
		@Transportista,
		@RucTransportista,
		@TipoTransporte,
		@EsContable,
		@AuxVar1,
		@AuxVar2,
		@AuxVar3,
		@AuxVar4,
		@AuxVar5,
		@AuxVar6,
		@AuxVar7,
		@AuxVar8,
		@AuxVar9,
		@AuxVar10,
		@AuxVar11,
		@AuxVar12,
		@AuxFec1,
		@AuxFec2,
		@AuxFec3,
		@AuxLog1,
		@AuxLog2,
		@AuxLog3,
		@AuxNum1,
		@AuxNum2,
		@AuxNum3,
		@AuxNum4,
		@AuxNum5,
		@AuxNum6,
		@AuxNum7,
		@AuxNum8,
		@AuxNum9,
		@AuxNum10,
		@AuxNum11,
		@AuxNum12,
		@doc_Anticipo,
		@Consolidar,
		@TipDocConsolida,
		@NroDocConsolida,
		@Contabilizar,
		@ProductoProduccion,
		@Mesero,
		@BaseImp1,
		@BaseImp2,
		@BaseImp3,
		@PorcImp1,
		@PorcImp2,
		@PorcImp3,
		@ValorImp1,
		@ValorImp2,
		@ValorImp3,
		@Ocupantes)
END