if exists(select * from sys.objects where name ='ADCTRA_GENERAR_INV')
begin
DROP PROCEDURE [dbo].[ADCTRA_GENERAR_INV]
end
GO

 CREATE PROCEDURE [dbo].[ADCTRA_GENERAR_INV]
 (
	@Doc_sucursal char(3)='',	
	@Doc_Bodega char(3)='',	
	@Opc_documento char(3)='',	
	@Doc_numero numeric(18,0)=0,	
	@Tra_TipoDoc varchar(3)='',	
	@Tra_DocSop varchar(3)='',	
	@Tra_NumSop numeric(18,0)=0,	
	@Tra_numlinea numeric(18,0)=0,	
	@Tra_Codigo varchar(20)='',	
	@Tra_docotro varchar(3)='',	
	@Tra_numotro numeric(18,0)=0,
	@Tra_fecha datetime =null,	
	@Tra_nombre varchar(120)='',	
	@Tra_cantidad numeric(22,8)=0,	
	@Tra_costuni numeric(22	,8)=0,
	@Tra_costtot numeric(22	,8)=0,
	@Tra_numprecio varchar(1)='',	
	@Tra_descdes varchar(40)='',	
	@Tra_porcendes numeric(19,4)=0,	
	@Tra_valordes numeric(19,4)=0,	
	@Tra_valor numeric(19,4)=0,	
	@Tra_extension varchar(15)='',	
	@Tra_sniva bit=0,	
	@Tra_Individual varchar(3)='',
	@Tra_quetipo varchar(1)='',	
	@Tra_precuni numeric(22,8)=0,	
	@Tra_prectot numeric(22,8)=0,	
	@Tra_DepDes varchar(50)='',	
	@Tra_Estado smallint=0,	
	@Tra_Oculto smallint=0,	
	@Tra_Inventario smallint=0,
	@Tra_Ventas smallint=0,	
	@Tra_Compras smallint=0,	
	@Tra_Activo smallint=0	,
	@Tra_Adicional1 numeric(19,4)=0,	
	@Tra_Adicional2 numeric(19,4)=0,	
	@Tra_piezas numeric(18,0)=0,	
	@Tra_medida varchar(5)='',	
	@Tra_multiplo numeric(22,8)=0,	
	@Tra_vence datetime =null,	
	@tra_Serie varchar(20)='',
	@IdClaveDoc numeric(18,0)=0,	
	@Tra_NroLote varchar(20)='',	
	@Tra_NroLoteDoc varchar(20)='',	
	@Periodo1 datetime=null,	
	@Periodo2 datetime =null,	
	@FacDesde datetime =null,	
	@FacHasta datetime =null	
 )
 AS
 BEGIN
 insert into AdcTra 
 (
	Doc_sucursal,
	Doc_Bodega,
	Opc_documento,
	Doc_numero,
	Tra_TipoDoc,
	Tra_DocSop,
	Tra_NumSop,
	Tra_numlinea,
	Tra_Codigo,
	Tra_docotro,
	Tra_numotro,
	Tra_fecha,
	Tra_nombre,
	Tra_cantidad,
	Tra_costuni,
	Tra_costtot,
	Tra_numprecio,
	Tra_descdes,
	Tra_porcendes,
	Tra_valordes,
	Tra_valor,
	Tra_extension,
	Tra_sniva,
	Tra_Individual,
	Tra_quetipo,
	Tra_precuni,
	Tra_prectot,
	Tra_DepDes,
	Tra_Estado,
	Tra_Oculto,
	Tra_Inventario,
	Tra_Ventas,
	Tra_Compras,
	Tra_Activo,
	Tra_Adicional1,
	Tra_Adicional2,
	Tra_piezas,
	Tra_medida,
	Tra_multiplo,
	Tra_vence,
	tra_Serie,
	IdClaveDoc,
	Tra_NroLote,
	Tra_NroLoteDoc,
	Periodo1,
	Periodo2,
	FacDesde,
	FacHasta
 )
 values
 (
	@Doc_sucursal,
	@Doc_Bodega,
	@Opc_documento,
	@Doc_numero,
	@Tra_TipoDoc,
	@Tra_DocSop,
	@Tra_NumSop,
	@Tra_numlinea,
	@Tra_Codigo,
	@Tra_docotro,
	@Tra_numotro,
	@Tra_fecha,
	@Tra_nombre,
	@Tra_cantidad,
	@Tra_costuni,
	@Tra_costtot,
	@Tra_numprecio,
	@Tra_descdes,
	@Tra_porcendes,
	@Tra_valordes,
	@Tra_valor,
	@Tra_extension,
	@Tra_sniva,
	@Tra_Individual,
	@Tra_quetipo,
	@Tra_precuni,
	@Tra_prectot,
	@Tra_DepDes,
	@Tra_Estado,
	@Tra_Oculto,
	@Tra_Inventario,
	@Tra_Ventas,
	@Tra_Compras,
	@Tra_Activo,
	@Tra_Adicional1,
	@Tra_Adicional2,
	@Tra_piezas,
	@Tra_medida,
	@Tra_multiplo,
	@Tra_vence,
	@tra_Serie,
	@IdClaveDoc,
	@Tra_NroLote,
	@Tra_NroLoteDoc,
	@Periodo1,
	@Periodo2,
	@FacDesde,
	@FacHasta )
 END